package com.example.kotlin_app.data.dto

import com.example.kotlin_app.domain.model.StockItem

// Generated by JsonKotlin Api
data class YahooResultDto(
    var chart: Chart
) {
    data class Chart(
        var error: Any?,
        var result: List<Result>
    ) {
        data class Result(
            var indicators: Indicators,
            var meta: Meta,
            var timestamp: List<Int>
        ) {
            data class Indicators(
                var adjclose: List<Adjclose>,
                var quote: List<Quote>
            ) {
                data class Adjclose(
                    var adjclose: List<Double>
                )

                data class Quote(
                    var close: List<Double>,
                    var high: List<Double>,
                    var low: List<Double>,
                    var `open`: List<Double>,
                    var volume: List<Int>
                )
            }

            data class Meta(
                var chartPreviousClose: Double,
                var currency: String,
                var currentTradingPeriod: CurrentTradingPeriod,
                var dataGranularity: String,
                var exchangeName: String,
                var exchangeTimezoneName: String,
                var fiftyTwoWeekHigh: Double,
                var fiftyTwoWeekLow: Double,
                var firstTradeDate: Int,
                var fullExchangeName: String,
                var gmtoffset: Int,
                var hasPrePostMarketData: Boolean,
                var instrumentType: String,
                var longName: String,
                var priceHint: Int,
                var range: String,
                var regularMarketDayHigh: Double,
                var regularMarketDayLow: Double,
                var regularMarketPrice: Double,
                var regularMarketTime: Int,
                var regularMarketVolume: Int,
                var shortName: String,
                var symbol: String,
                var timezone: String,
                var validRanges: List<String>
            ) {
                data class CurrentTradingPeriod(
                    var post: Post,
                    var pre: Pre,
                    var regular: Regular
                ) {
                    data class Post(
                        var end: Int,
                        var gmtoffset: Int,
                        var start: Int,
                        var timezone: String
                    )

                    data class Pre(
                        var end: Int,
                        var gmtoffset: Int,
                        var start: Int,
                        var timezone: String
                    )

                    data class Regular(
                        var end: Int,
                        var gmtoffset: Int,
                        var start: Int,
                        var timezone: String
                    )
                }
            }
        }
    }
}

fun YahooResultDto.toStockItem() : StockItem = StockItem(
    symbol = chart.result.first.meta.symbol,
    longName = chart.result.first.meta.longName,
    regularMarketPrice = chart.result.first.meta.regularMarketPrice,
)